# Site settings
title: "Jektify"
email: william.costa.canin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jektify is a Gem for entering track, playlist, albums and artists in Jekyll templates.
# Urls production
# baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://localhost:4000" # the base hostname & protocol for your site

baseurl: "/jektify" # the subpath of your site, e.g. /blog/
url: "https://williamcanin.me" # the base hostname & protocol for your site.

# Change version!!!
header:
  name: "jektify"
  url_download: "https://rubygems.global.ssl.fastly.net/gems"
  lasted_version: "1.0.0"

# Build settings
destination: ./_site
markdown: kramdown

# Permilink
permalink: /:title/

# Excluded for build
exclude: ["_vendor","Gemfile","*.lock","gh-pages.sh","deploy.sh"]

plugins:
  - bootstrap
  - jekyll-spotify-plugin

# ----------------------------------------------------------------------
# Jekyll Spotify - Configuration for _config.yml
# Insert this code in your template
#
spotify:
  enable: true
  open: false
  toggle:
    using: true
  user:
    name: williamcanin
    text: See me no Spotify
  sass:
    jekyll: true
    dir: "_sass/vendor"
  title:
    enable: true
    text: "Jekyll Spotify Plugin"
  description:
    enable: true
    text: |
      Jekyll plugin to generate html snippets for embedding Spotify Musics.
      To listen to the full song, open your Spotify and start these musics.
#
# ----------------------------------------------------------------------
